# Build examples with Platformio
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# https://docs.platformio.org/en/latest/integration/ci/github-actions.html

name: PlatformIO CI

on:
  workflow_dispatch:      # Manual start
  push:
    #branches: [ main, feat ]
    paths:
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**.ini'
    - '**.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - "examples/asyncserver-flashz"
          - "examples/httpserver-flashz"

    steps:
    - uses: actions/checkout@v4
    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install Platformio
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        #pio update
    - name: Run PlatformIO
      env: 
        PLATFORMIO_CI_SRC: ${{ matrix.example }}
      run: |
        cd ${{ matrix.example }} && platformio run -e flashz -e flashz_debug
        #pio ci -c ${{ matrix.example }}/platformio.ini
